import { IconType } from "react-icons";

import {
  HiArrowUpRight,
  HiOutlineLink,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineDocument,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineRocketLaunch,
} from "react-icons/hi2";

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
  PiBriefcaseDuotone,
} from "react-icons/pi";

import {
  SiJavascript,
  SiNextdotjs,
  SiFigma,
  SiSupabase,
  SiTailwindcss,
  SiTypescript,
  SiVite,
  SiCypress,
  SiStreamlabs,
  SiStreamlit,
  SiDjango,
  SiFlask,
  SiNodedotjs,
  SiExpress,
  SiMonero,
  SiMongodb,
  SiDocker,
  SiLinux,
  SiGit,
  SiNumpy,
  SiLangchain,
  SiOpencv,
  SiApachemaven,
  SiJira,
} from "react-icons/si";

import {
  FaDiscord,
  FaGithub,
  FaLinkedin,
  FaX,
  FaThreads,
  FaInstagram,
  FaXTwitter,
  FaFacebook,
  FaPinterest,
  FaWhatsapp,
  FaReddit,
  FaTelegram,
  FaPython,
  FaJava,
  FaHtml5,
  FaAws,
} from "react-icons/fa6";
import { TbBrandCpp, TbBrandReactNative, TbFileTypeSql } from "react-icons/tb";
import { RiReactjsFill } from "react-icons/ri";
import { FaLaptop } from "react-icons/fa";

export const iconLibrary: Record<string, IconType> = {
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  email: HiEnvelope,
  globe: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: FaLaptop,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  briefcase: PiBriefcaseDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaX,
  twitter: FaXTwitter,
  threads: FaThreads,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  javascript: SiJavascript,
  nextjs: SiNextdotjs,
  supabase: SiSupabase,
  figma: SiFigma,
  facebook: FaFacebook,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaReddit,
  telegram: FaTelegram,
  instagram: FaInstagram,
  python: FaPython,
  typescript: SiTypescript,
  java: FaJava,
  cpp: TbBrandCpp,
  HTML: FaHtml5,
  tailwindcss: SiTailwindcss,
  reactjs: RiReactjsFill,
  vitejs: SiVite,
  reactnative: TbBrandReactNative,
  cypress: SiCypress,
  streamlit: SiStreamlit,
  Django: SiDjango,
  flask: SiFlask,
  nodejs: SiNodedotjs,
  expressjs: SiExpress,
  mongodb: SiMongodb,
  docker: SiDocker,
  linux: SiLinux,
  git: SiGit,
  numpy: SiNumpy,
  langchain: SiLangchain,
  opencv: SiOpencv,
  maven: SiApachemaven,
  jira: SiJira,
  sql: TbFileTypeSql,
  aws: FaAws
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
